# Generated by Django 4.0.3 on 2023-09-08 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_alter_appointment_vip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automobilevo',
            old_name='import_herf',
            new_name='import_href',
        ),
    ]
